version: '2'
services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile
    container_name: cryptofiat-geth
    volumes:
      - ./geth/.ethash:/root/.ethash:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  config:
    depends_on: 
      - contracts
    image: hyness/spring-cloud-config-server
    container_name: cryptofiat-config
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config
    volumes:
      - eth-config:/config
    ports:
      - "8888:8888"
  contracts:
    depends_on: 
      - geth
    container_name: cryptofiat-contracts
    build: 
      context: ../
      dockerfile: test-environment/Dockerfile
    volumes:
      - eth-config:/config
volumes:
  eth-config:
  