version: '2'
services:
  geth:
    image: ethereum/client-go
    container_name: cryptofiat
    entrypoint: /root/geth.sh
    volumes:
      - ./docker/geth.sh:/root/geth.sh:ro
      - ./docker/genesis.json:/root/files/genesis.json:ro
      - ./docker/keystore:/root/.ethereum/devchain/keystore:rw
      - ./docker/.ethash:/root/.ethash:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  config:
    image: hyness/spring-cloud-config-server
    container_name: cryptofiat-config
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config
    volumes:
      - ./application.yml:/config/application.yml:ro
    ports:
      - "8888:8888"